# Generated by Django 5.1.7 on 2025-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0002_videoasset_original_cover_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='explain_video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
