# Generated by Django 5.1.7 on 2025-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0003_videoasset_explain_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='descriptions_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='explain_srt_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
