# Generated by Django 5.1.7 on 2025-05-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0004_videoasset_descriptions_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='explain_cover_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
