# Generated by Django 5.1.7 on 2025-05-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Log Viewer',
                'verbose_name_plural': 'Log Viewer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('log_viewer.logentry',),
        ),
    ]
